Repository SafiraSari/group-to-go, pull requests merged in 2025-04, with the labels that each got.

#6 Modal Component
  README.md
  public/favicon.ico
  src/App.js
  src/assets/logo.png
  src/assets/logo_horizontal.png
  src/assets/logo_square.png
  src/assets/option_activity.png
  src/assets/option_budget.png
  src/assets/option_food.png
  src/assets/option_poll.png
  src/assets/option_time.png
  src/assets/schedule1.png
  src/components/Button.css
  src/components/Button.js
  src/components/Input.css
  src/components/Input.js
  src/components/Modal.css
  src/components/Modal.js
  src/components/NavBar.css
  src/constants.css
  src/index.css
  src/pages/Login.css
  src/pages/Login.js
  src/pages/Polls.css
  src/pages/Polls.js
  src/pages/Signup.css
Labels: feature, fix

#8 Expense Tracker
  src/components/Modal.css
  src/pages/Expense.css
  src/pages/Expenses.js
Labels: feature

#12 Switched to Firebase for the database
  .gitignore
  backend/FirebaseConfig.js
  backend/GroupToGoDB.sql
  backend/server.js
  src/pages/Signup.css
  src/pages/Signup.js
Labels: api/db, fix

#13 README, Confirmation Modal & NavBar Active Tab
  .gitignore
  README.md
  backend/FirebaseConfig.js
  backend/server.js
  public/index.html
  src/assets/animations/signup.lottie
  src/assets/lottieanimations/login.lottie
  src/assets/schedule1.png
  src/components/Confirmation.css
  src/components/Confirmation.js
  src/components/NavBar.css
  src/components/NavBar.js
  src/pages/Login.css
  src/pages/Polls.css
  src/pages/Signup.css
  src/pages/Signup.js
Labels: documentation, feature, refactor

#21 Groups
  backend/server.js
  src/pages/Groups.css
  src/pages/Groups.js
  src/pages/Login.js
Labels: feature, api/db

#23 Maps Page
  src/App.js
  src/assets/favoriteempty.png
  src/assets/favoritefilled.png
  src/assets/favoriteplace.png
  src/assets/map.png
  src/components/Input.js
  src/components/NavBar.js
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/pages/Map.css
  src/pages/Map.js
Labels: feature, api/db

#24 Landing Page
  README.md
  package-lock.json
  package.json
  src/App.js
  src/assets/home.png
  src/components/Modal.js
  src/components/NavBar.js
  src/pages/Home.css
  src/pages/Home.js
  src/pages/Landing.css
  src/pages/Landing.js
  src/pages/Login.js
  src/pages/Polls.css
  src/pages/Polls.js
Labels: feature

#27 Expense tracker
  backend/server.js
  src/components/Modal.js
  src/pages/Expense.css
  src/pages/Expenses.js
Labels: feature, api/db

#28 Feature/polls complete
  README.md
  backend/server.js
  package-lock.json
  package.json
  src/components/Accordion.js
  src/pages/Polls.css
  src/pages/Polls.js
Labels: feature, api/db

#25 Event Creation & Schedule
  README.md
  backend/server.js
  src/components/Modal.js
  src/components/NavBar.js
  src/pages/Events.css
  src/pages/Events.js
  src/pages/Expense.css
  src/pages/Schedule.css
  src/pages/Schedule.js
Labels: feature, api/db
